"use client";
import { useMemo, useState } from "react";
import { buildPrompt, PromptMode, promptModes, SessionContext } from "@/lib/prompts";
import { buildDepthGuide, deepObjective } from "@/lib/sessionDepth";

const labels:Record<string,string>={goal:"Goal",currentLevel:"Current level",targetLevel:"Target level",targetRole:"Target role",level:"Interview level",duration:"Duration",studentAnswer:"Your explanation from memory",questionCount:"Question count",sourceMaterial:"Source material / notes"};
const multiline=new Set(["currentLevel","targetLevel","studentAnswer","sourceMaterial"]);

export default function PromptStudio({initialTopic="",sessionContext={}}:{initialTopic?:string;sessionContext?:SessionContext}){
  const [mode,setMode]=useState<PromptMode>(sessionContext.sessionSlug?"session":"teacher");
  const [values,setValues]=useState<Record<string,string>>({goal:"Microsoft software-engineering interview preparation",currentLevel:"I know the basics, but I want interview-grade recall and explanation.",targetLevel:"I can explain it cold, compare alternatives, apply it, debug it and survive follow-up questions.",targetRole:"Microsoft Software Engineer — cloud/platform/backend",level:"IC2–IC3 / junior-to-mid",duration:"30 minutes",questionCount:"30",studentAnswer:"",sourceMaterial:""});
  const [response,setResponse]=useState(""); const [status,setStatus]=useState(""); const [saved,setSaved]=useState(false);
  const selected=promptModes.find(x=>x.id===mode)!; const prompt=useMemo(()=>buildPrompt(mode,values,sessionContext),[mode,values,sessionContext]);
  const depthGuide=useMemo(()=>sessionContext.sessionSlug?buildDepthGuide({title:sessionContext.sessionTitle,objective:sessionContext.objective,scope:sessionContext.scope,outcomes:sessionContext.outcomes,track:sessionContext.track}):[],[sessionContext]);
  const deepGoal=useMemo(()=>sessionContext.sessionSlug?deepObjective({title:sessionContext.sessionTitle,objective:sessionContext.objective,scope:sessionContext.scope,outcomes:sessionContext.outcomes,track:sessionContext.track}):"",[sessionContext]);
  const set=(k:string,v:string)=>setValues(x=>({...x,[k]:v}));
  async function copyPrompt(open=false){await navigator.clipboard.writeText(prompt);if(open)window.open("https://chatgpt.com/","_blank","noopener,noreferrer");setStatus("Prompt copied.");}
  async function saveSession(){await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,topic:initialTopic,roadmapSessionSlug:sessionContext.sessionSlug,prompt,response})});setSaved(true);setTimeout(()=>setSaved(false),1500);}
  async function importQuestions(){try{const text=response.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const data=JSON.parse(text);const r=await fetch("/api/questions/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error||"Import failed");setStatus(`Imported ${out.inserted} questions.`);}catch(e:any){setStatus(`Import failed: ${e.message}`)}}
  return <div className="prompt-layout">
    <div className="mode-list">{promptModes.map(m=><button key={m.id} className={`mode-btn ${mode===m.id?"active":""}`} onClick={()=>{setMode(m.id);setResponse("");setStatus("")}}><div className="mode-name">{m.name}</div><div className="mode-short">{m.short}</div></button>)}</div>
    <div className="grid" style={{gap:16}}>
      {sessionContext.sessionSlug&&<div className="session-brief card"><div className="eyebrow">Current bounded session · depth-first</div><div className="session-brief-head"><div><h2>{sessionContext.sessionTitle}</h2><p>{deepGoal}</p></div><span className="badge accent">{sessionContext.sessionIndex}/{sessionContext.sessionCount}</span></div><div className="chips">{sessionContext.scope?.map(x=><span className="chip" key={x}>{x}</span>)}</div><div className="deep-contract"><div className="deep-contract-title">Deep understanding means</div><ul>{depthGuide.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="boundary-note">Depth, not breadth: anything outside this exact scope is explicitly deferred to another session.</div></div>}
      <div className="card"><div className="section-head"><div><div className="eyebrow">Template</div><h2>{selected.name}</h2></div><span className="badge accent">ChatGPT bridge / no API</span></div><div className="form-grid">{selected.fields.map(f=><div className="field" key={f} style={multiline.has(f)?{gridColumn:"1 / -1"}:undefined}><label>{labels[f]||f}</label>{multiline.has(f)?<textarea className="textarea" value={values[f]||""} onChange={e=>set(f,e.target.value)}/>:<input className="input" value={values[f]||""} onChange={e=>set(f,e.target.value)}/>}</div>)}</div></div>
      <div className="card"><div className="section-head"><div><div className="eyebrow">Generated handoff</div><h2>One-chat prompt</h2></div><div className="actions"><button className="btn small secondary" onClick={()=>copyPrompt(false)}>Copy</button><button className="btn small accent" onClick={()=>copyPrompt(true)}>Copy + open ChatGPT ↗</button></div></div><div className="prompt-box">{prompt}</div>{status&&<div className="inline-status">{status}</div>}</div>
      <div className="card"><div className="section-head"><div><div className="eyebrow">Bring the result home</div><h2>Capture output</h2></div><button className="btn small" onClick={saveSession}>{saved?"Saved ✓":"Save chat record"}</button></div><p className="section-note">Paste useful critique, notes, or final revision-question JSON here. The Session Coach can generate importable questions at the end of the same chat.</p><textarea className="textarea response-area" value={response} onChange={e=>setResponse(e.target.value)} placeholder="Paste the useful result from this ChatGPT session…"/><div className="actions"><button className="btn accent" onClick={importQuestions}>Import JSON → Question Bank</button><span className="muted" style={{alignSelf:"center"}}>Safe to click only when the box contains question JSON.</span></div></div>
    </div>
  </div>
}
