"use client";
import { ChangeEvent, useEffect,useState } from "react";
import QuestionCard,{Question} from "@/components/QuestionCard";

export default function QuestionBank({initialTopic=""}:{initialTopic?:string}){
  const [items,setItems]=useState<Question[]>([]);const [topics,setTopics]=useState<any[]>([]);const [topic,setTopic]=useState(initialTopic);const [type,setType]=useState("");const [difficulty,setDifficulty]=useState("");const [loading,setLoading]=useState(true);const [transfer,setTransfer]=useState("");
  async function load(){setLoading(true);const p=new URLSearchParams();if(topic)p.set("topic",topic);if(type)p.set("type",type);if(difficulty)p.set("difficulty",difficulty);const r=await fetch(`/api/questions?${p}`);setItems(await r.json());setLoading(false)}
  useEffect(()=>{fetch("/api/topics").then(r=>r.json()).then(setTopics)},[]);useEffect(()=>{load()},[topic,type,difficulty]);async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{setTransfer("Importing…");const data=JSON.parse(await file.text());const r=await fetch("/api/questions/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error||"Import failed");setTransfer(`Imported ${out.inserted} questions.`);await load()}catch(err:any){setTransfer(`Import failed: ${err.message}`)}finally{e.target.value=""}}
  return <><div className="transfer-bar card-flat"><div><strong>Question data</strong><div className="muted">Import a Recall Forge JSON export or download all non-seed questions from this PostgreSQL database.</div>{transfer&&<div className="inline-status">{transfer}</div>}</div><div className="actions"><label className="btn small secondary file-btn">Import JSON<input type="file" accept="application/json,.json" onChange={importFile}/></label><a className="btn small ghost" href="/api/data/export">Export my questions</a></div></div><div className="filters"><select className="select" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{topics.map(t=><option value={t.slug} key={t.slug}>{t.track} — {t.title}</option>)}</select><select className="select" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{["recall","explain","compare","application","debug","design","cross_topic","misconception"].map(x=><option key={x}>{x}</option>)}</select><select className="select" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All levels</option>{[1,2,3,4,5,6].map(x=><option value={x} key={x}>L{x}</option>)}</select><button className="btn secondary" onClick={load}>Refresh</button></div>{loading?<div className="empty">Loading question bank…</div>:items.length===0?<div className="empty">No questions match these filters. Finish a concrete roadmap session and import its revision-question JSON.</div>:<div className="question-list">{items.map(q=><QuestionCard q={q} key={q.id} onReviewed={u=>setItems(v=>v.map(x=>x.id===u.id?u:x))}/>)}</div>}</>
}
