"use client";
import { useRef, useState } from "react";

export type Question = {
  id:string; externalId?:string|null; topicSlug:string; sessionSlug?:string|null; type:string; format?:"open"|"multi_select"|string; difficulty:number;
  questionMd:string; answerMd:string; options?:string[]; correctOptionIndexes?:number[]; optionFeedback?:{rationale:string;concepts:string[]}[]; concepts?:string[]; relatedQuestionIds?:string[]; prerequisiteQuestionIds?:string[]; subtopics?:string[]; prerequisites?:string[]; keyPoints?:string[]; hints?:{level:number;text:string}[]; commonMistakes?:string[];
  expectedMinutes?:number; tags?:string[]; nextReviewAt?:string|Date; repetitions?:number; intervalDays?:number;
  lastPrintedAt?:string|Date|null; printCount?:number; createdAt?:string|Date;
};

export default function QuestionCard({q,onReviewed,showReview=true}:{q:Question;onReviewed?:(q:Question)=>void;showReview?:boolean}){
  const [open,setOpen]=useState(false); const [hintCount,setHintCount]=useState(0); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<Set<number>>(new Set()); const [mcResult,setMcResult]=useState<any>(null); const startedAt=useRef(Date.now());
  async function grade(value:"again"|"hard"|"good"|"easy") {setBusy(true);const r=await fetch(`/api/questions/${q.id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({grade:value})});const updated=await r.json();setBusy(false);if(r.ok){setOpen(false);setHintCount(0);onReviewed?.(updated)}}
  async function submitMulti(){setBusy(true);const r=await fetch("/api/revision/attempt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:q.id,selectedOptionIndexes:Array.from(selected),responseMs:Date.now()-startedAt.current})});const out=await r.json();setBusy(false);if(!r.ok)return alert(out.error||"Could not record answer");setMcResult(out);setOpen(true)}
  const hints=q.hints||[]; const isMulti=q.format==="multi_select";
  return <article className="question-card">
    <div className="question-head">
      <div className="question-meta"><span className="badge level">L{q.difficulty}</span><span className="badge">{q.type}</span>{isMulti&&<span className="badge accent">0–4 correct</span>}<span className="badge accent">{q.topicSlug}</span>{q.sessionSlug&&<span className="badge session-badge">{q.sessionSlug}</span>}{q.expectedMinutes?<span className="badge">~{q.expectedMinutes} min</span>:null}</div>
      <div className="question-text">{q.questionMd}</div>
      {isMulti?<div className="review-multi-options">{(q.options||[]).map((option,i)=>{const chosen=selected.has(i);const correct=(q.correctOptionIndexes||[]).includes(i);const state=mcResult?(correct?"correct":chosen?"wrong":"neutral"):chosen?"chosen":"";return <button key={i} disabled={!!mcResult||busy} className={`review-multi-option ${state}`} onClick={()=>setSelected(cur=>{const n=new Set(cur);n.has(i)?n.delete(i):n.add(i);return n})}><span>{String.fromCharCode(65+i)}</span><strong>{option}</strong>{mcResult&&<b>{correct?"✓":chosen?"×":""}</b>}</button>})}<div className="actions"><span className="muted">Choose any number, including none.</span>{!mcResult?<button className="btn small accent" disabled={busy} onClick={submitMulti}>{busy?"Checking…":"Submit"}</button>:showReview?<button className="btn small accent" onClick={()=>onReviewed?.(mcResult.question)}>Next →</button>:null}</div></div>:<div className="actions review-actions">{hints.length>0&&hintCount<hints.length&&<button className="btn small ghost" onClick={()=>setHintCount(c=>c+1)}>Hint {hintCount+1}</button>}<button className="btn small secondary reveal-btn" onClick={()=>setOpen(v=>!v)}>{open?"Hide answer ↑":"Show answer ↓"}</button></div>}
      {!isMulti&&hintCount>0&&<div className="card-flat hint-box">{hints.slice(0,hintCount).map((h,i)=><div key={i}><span className="mono muted">H{i+1}</span> {h.text}</div>)}</div>}
    </div>
    {open&&<div className="answer"><div className="answer-title">Expected answer</div><div className="answer-body">{q.answerMd}</div>{isMulti&&!!q.optionFeedback?.length&&<div className="review-option-rationales">{q.optionFeedback.map((fb,i)=><div key={i}><b>{String.fromCharCode(65+i)}</b><span>{fb.rationale}</span></div>)}</div>}{!!q.keyPoints?.length&&<><div className="answer-title answer-subtitle">Full-credit points</div><ul className="keypoints">{q.keyPoints.map((x,i)=><li key={i}>{x}</li>)}</ul></>}{!!q.commonMistakes?.length&&<><div className="answer-title answer-subtitle">Common traps</div><ul className="keypoints">{q.commonMistakes.map((x,i)=><li key={i}>{x}</li>)}</ul></>}</div>}
    {showReview&&open&&!isMulti&&<div className="review-bar"><span className="muted review-prompt">Grade what you knew <strong>before</strong> reveal.</span><div className="grade-buttons"><button disabled={busy} className="grade-button again" onClick={()=>grade("again")}><strong>Again</strong><small>10m</small></button><button disabled={busy} className="grade-button hard" onClick={()=>grade("hard")}><strong>Hard</strong><small>short</small></button><button disabled={busy} className="grade-button good" onClick={()=>grade("good")}><strong>Good</strong><small>normal</small></button><button disabled={busy} className="grade-button easy" onClick={()=>grade("easy")}><strong>Easy</strong><small>long</small></button></div></div>}
  </article>
}
